# Generated by Django 4.1.7 on 2024-04-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='file',
            new_name='resume_file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_at',
        ),
    ]
