# Generated by Django 4.1.7 on 2024-04-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_builder', '0002_rename_file_resume_resume_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(default='Add Your Summry', max_length=5000)),
                ('skills', models.CharField(default='Add Your Skills', max_length=5000)),
            ],
        ),
    ]
